"use client"
import React, { createContext, useContext, useState, useEffect } from "react"
export const dict: any = {
  en: {
    navHome:"Home", navAbout:"About", navWhere:"Where We Work", navImpact:"Impact", navProjects:"Projects", navSponsors:"Sponsors", navTrans:"Transparency", navZakat:"Zakat", navDonate:"Donate →",
    hero1:"Bridging Continents,", hero2:"Building Hope", heroSub:"Your donation delivers clean water, education and healthcare across Africa. 100% transparent, Zakat-eligible, video proof.", heroBtn:"Donate Now → $50 = 1 Month Water", give:"Give Hope Today", live:"LIVE", live21:"LIVE 21", donateNow:"Donate Now",
    global:"Global Presence", globalSub:"Istanbul & Baku to 22 nations", globalMap:"Türkiye • Azerbaijan • USA • UK • Uganda • Somalia • Niger", globalClick:"Click to explore →", lives:"Lives", projects:"Projects", countries:"Countries",
    story:"Our Story", since:"SINCE 2021", storyDesc:"Founded 2021, born from idea: Turkish & Azerbaijani compassion can change Africa. Every donation tracked, filmed, reported. 89% field.", storyBtn:"Read Our Story →",
    impactT:"2024 Impact", water:"Clean Water", waterSub:"78k • 156 wells", edu:"Education", eduSub:"3k • 12 schools", health:"Healthcare", healthSub:"15k • 4 clinics", viewProjects:"View All Projects →",
    urgent:"Urgent Appeals", viewAll:"View All 45 →", ramadan:"Ramadan Food Parcels", orphan:"Orphan Sponsorship", well:"Deep Water Well – 800 People",
    how:"How Your Donation Becomes Hope • 100% Tracked", s1t:"You Donate", s1d:"Card, PayPal, Troy, BirKart – SSL 256-bit secure", s2t:"We Deploy 72H", s2d:"Local team Kampala / Niamey starts in 72 hours", s3t:"You Get Proof", s3d:"Drone, interviews, GPS, name plate video", s4t:"Impact Report", s4d:"Audited report, dashboard, tax receipt",
    proof:"Live Proof Feed • Last 24 Hours", proof1:"Well #157 opened – 840 people now have water", proof2:"120 food parcels delivered – video proof", proof3:"Clinic treated 34 children today",
    sponsorT:"Corporate Sponsorship Tiers • Turkish & Azerbaijani Companies", bronze:"Bronze • $1k-$5k", bronzeD:"1 well or 30 food kits • Logo on site", silver:"Silver • $5k-$15k", silverD:"3 wells or 1 classroom • Certificate", gold:"Gold • $15k-$50k", goldD:"Full school • Name on building • Press", platinum:"Platinum • $50k+", platinumD:"Village complex • Naming rights • Documentary", viewTier:"View Tier →",
    donorWall:"Live Donor Wall", donorLive:"LIVE", zakatT:"Zakat Calculator • 2.5%", zakatSub:"Enter total wealth (gold, savings, trade)", zakatWealth:"Wealth", zakatDue:"Zakat Due", zakatBtn:"Donate Zakat Now →", calcPlaceholder:"2500",
    videoT:"Every Donation Has Video Proof • 100% Transparent", videoSub:"Drone footage, beneficiary interviews, GPS coordinates",
    trustT:"Trusted & Secure • 89% Goes to Field", finalT1:"Name a Well Today", finalT2:"After Your Family", finalSub:"Your family name on a well plate in Uganda • Video + GPS + Certificate in 7 days", finalBtn:"Donate a Well – $2,500 →", whatsapp:"WhatsApp Us",
    footerLinks:"Links", footerGive:"Give", footerStory:"Our Story", footerWhere:"Where We Work", footerZakat:"Zakat Calculator", footerDonate:"Donate Now",
    trLabel:"Türkiye", azLabel:"Azerbaijan",
  },
  tr: {
    navHome:"Ana Sayfa", navAbout:"Hakkımızda", navWhere:"Nerede Çalışıyoruz", navImpact:"Etki", navProjects:"Projeler", navSponsors:"Sponsorlar", navTrans:"Şeffaflık", navZakat:"Zekat", navDonate:"Bağış Yap →",
    hero1:"Kıtaları Birleştiren,", hero2:"Umut İnşa Eden", heroSub:"Bağışınız Afrika'ya temiz su, eğitim ve sağlık ulaştırır. %100 şeffaf, Zekat uygun, video kanıtlı.", heroBtn:"Bağış Yap → $50 = 1 Ay Su", give:"Bugün Umut Ver", live:"CANLI", live21:"CANLI 21", donateNow:"Bağış Yap",
    global:"Küresel Varlık", globalSub:"İstanbul & Bakü'den 22 ülkeye", globalMap:"Türkiye • Azerbaycan • ABD • İngiltere • Uganda • Somali • Nijer", globalClick:"Keşfetmek için tıkla →", lives:"Yaşam", projects:"Proje", countries:"Ülke",
    story:"Hikayemiz", since:"2021'DEN BERİ", storyDesc:"2021'de kuruldu, Türk ve Azerbaycan şefkatinin Afrika'yı değiştirebileceği fikrinden doğdu. Her bağış takip edilir, filme alınır, raporlanır. %89 sahada.", storyBtn:"Hikayemizi Oku →",
    impactT:"2024 Etki", water:"Temiz Su", waterSub:"78k • 156 kuyu", edu:"Eğitim", eduSub:"3k • 12 okul", health:"Sağlık", healthSub:"15k • 4 klinik", viewProjects:"Tüm Projeleri Gör →",
    urgent:"Acil Çağrılar", viewAll:"Tümünü Gör 45 →", ramadan:"Ramazan Gıda Kolileri", orphan:"Yetim Sponsorluğu", well:"Derin Su Kuyusu – 800 Kişi",
    how:"Bağışınız Nasıl Umuda Dönüşür • %100 Takip Edilir", s1t:"Bağış Yaparsın", s1d:"Kart, PayPal, Troy, BirKart – SSL 256-bit güvenli", s2t:"72 Saatte Dağıtıyoruz", s2d:"Yerel ekip Kampala / Niamey 72 saatte başlar", s3t:"Kanıt Alırsın", s3d:"Drone, röportaj, GPS, isim tabelası video", s4t:"Etki Raporu", s4d:"Denetlenmiş rapor, panel, vergi makbuzu",
    proof:"Canlı Kanıt Akışı • Son 24 Saat", proof1:"157 nolu kuyu açıldı – 840 kişi suya kavuştu", proof2:"120 gıda kolisi dağıtıldı – video kanıtlı", proof3:"Klinikte bugün 34 çocuk tedavi edildi",
    sponsorT:"Kurumsal Sponsorluk Seviyeleri • Türk & Azerbaycan Şirketleri", bronze:"Bronz • $1k-$5k", bronzeD:"1 kuyu veya 30 koli • Sitede logo", silver:"Gümüş • $5k-$15k", silverD:"3 kuyu veya 1 sınıf • Sertifika", gold:"Altın • $15k-$50k", goldD:"Tam okul • Binada isim • Basın", platinum:"Platin • $50k+", platinumD:"Köy kompleksi • İsim hakkı • Belgesel", viewTier:"Seviyeyi Gör →",
    donorWall:"Canlı Bağış Duvarı", donorLive:"CANLI", zakatT:"Zekat Hesaplayıcı • %2.5", zakatSub:"Toplam serveti gir (altın, birikim, ticaret)", zakatWealth:"Servet", zakatDue:"Zekat Tutarı", zakatBtn:"Zekat Bağışla →", calcPlaceholder:"2500",
    videoT:"Her Bağış Kanıtlı • %100 Şeffaf", videoSub:"Drone çekimi, faydalanıcı röportajları, GPS koordinatları",
    trustT:"Güvenilir & Güvenli • %89 Sahaya Gidiyor", finalT1:"Bugün Bir Kuyuya", finalT2:"Ailenizin İsmini Verin", finalSub:"Uganda'da kuyu tabelasında aile isminiz • 7 günde Video + GPS + Sertifika", finalBtn:"Kuyu Bağışla – $2,500 →", whatsapp:"WhatsApp Yaz",
    footerLinks:"Linkler", footerGive:"Bağış", footerStory:"Hikayemiz", footerWhere:"Nerede Çalışıyoruz", footerZakat:"Zekat Hesaplayıcı", footerDonate:"Bağış Yap",
    trLabel:"Türkiye", azLabel:"Azerbaycan",
  },
  az: {
    navHome:"Ana Səhifə", navAbout:"Haqqımızda", navWhere:"Harada İşləyirik", navImpact:"Təsir", navProjects:"Layihələr", navSponsors:"Sponsorlar", navTrans:"Şəffaflıq", navZakat:"Zəkat", navDonate:"Bağış Et →",
    hero1:"Qitələri Birləşdirən,", hero2:"Ümid Quran", heroSub:"Bağışınız Afrikaya təmiz su, təhsil və səhiyyə çatdırır. 100% şəffaf, Zəkat uyğun, video sübutlu.", heroBtn:"Bağış Et → $50 = 1 Ay Su", give:"Bu Gün Ümid Ver", live:"CANLI", live21:"CANLI 21", donateNow:"Bağış Et",
    global:"Qlobal Varlıq", globalSub:"İstanbul və Bakıdan 22 ölkəyə", globalMap:"Türkiyə • Azərbaycan • ABŞ • Böyük Britaniya • Uqanda • Somali • Niger", globalClick:"Kəşf etmək üçün kliklə →", lives:"Həyat", projects:"Layihə", countries:"Ölkə",
    story:"Hekayəmiz", since:"2021-DƏN BƏRİ", storyDesc:"2021-ci ildə quruldu, Türk və Azərbaycan şəfqətinin Afrikanı dəyişə biləcəyi ideyasından doğdu. Hər bağış izlənilir, çəkilir, hesabat verilir. 89% sahədə.", storyBtn:"Hekayəmizi Oxu →",
    impactT:"2024 Təsir", water:"Təmiz Su", waterSub:"78k • 156 quyu", edu:"Təhsil", eduSub:"3k • 12 məktəb", health:"Səhiyyə", healthSub:"15k • 4 klinika", viewProjects:"Bütün Layihələrə Bax →",
    urgent:"Təcili Çağırışlar", viewAll:"Hamısına Bax 45 →", ramadan:"Ramazan Ərzaq Bağlamaları", orphan:"Yetim Sponsorluğu", well:"Dərin Su Quyusu – 800 Nəfər",
    how:"Bağışınız Ümidə Necə Çevrilir • 100% İzlənir", s1t:"Sən Bağış Edirsən", s1d:"Kart, PayPal, Troy, BirKart – SSL 256-bit təhlükəsiz", s2t:"72 Saatda Çatdırırıq", s2d:"Yerli komanda Kampala / Niamey 72 saatda başlayır", s3t:"Sübut Alırsan", s3d:"Dron, müsahibə, GPS, ad lövhəsi video", s4t:"Təsir Hesabatı", s4d:"Audit edilmiş hesabat, panel, vergi qəbzi",
    proof:"Canlı Sübut Axını • Son 24 Saat", proof1:"157 nömrəli quyu açıldı – 840 nəfər suya qovuşdu", proof2:"120 ərzaq bağlaması çatdırıldı – video sübutlu", proof3:"Klinikada bu gün 34 uşaq müalicə olundu",
    sponsorT:"Korporativ Sponsorluq Səviyyələri • Türk və Azərbaycan Şirkətləri", bronze:"Bürünc • $1k-$5k", bronzeD:"1 quyu və ya 30 dəst • Saytda loqo", silver:"Gümüş • $5k-$15k", silverD:"3 quyu və ya 1 sinif • Sertifikat", gold:"Qızıl • $15k-$50k", goldD:"Tam məktəb • Binada ad • Mətbuat", platinum:"Platin • $50k+", platinumD:"Kənd kompleksi • Ad hüququ • Sənədli film", viewTier:"Səviyyəyə Bax →",
    donorWall:"Canlı İanə Divarı", donorLive:"CANLI", zakatT:"Zəkat Kalkulyatoru • 2.5%", zakatSub:"Ümumi sərvəti daxil et (qızıl, yığım, ticarət)", zakatWealth:"Sərvət", zakatDue:"Zəkat Məbləği", zakatBtn:"Zəkat Bağışla →", calcPlaceholder:"2500",
    videoT:"Hər Bağış Sübutludur • 100% Şəffaf", videoSub:"Dron çəkilişi, benefisiar müsahibələri, GPS koordinatları",
    trustT:"Etibarlı və Təhlükəsiz • 89% Sahəyə Gedir", finalT1:"Bu Gün Bir Quyuya", finalT2:"Ailənizin Adını Verin", finalSub:"Uqandada quyu lövhəsində ailə adınız • 7 günə Video + GPS + Sertifikat", finalBtn:"Quyu Bağışla – $2,500 →", whatsapp:"WhatsApp Yaz",
    footerLinks:"Linklər", footerGive:"Bağış", footerStory:"Hekayəmiz", footerWhere:"Harada İşləyirik", footerZakat:"Zəkat Kalkulyatoru", footerDonate:"Bağış Et",
    trLabel:"Türkiyə", azLabel:"Azərbaycan",
  },
  ar: { navHome:"الرئيسية", navAbout:"من نحن", navWhere:"أين نعمل", navImpact:"الأثر", navProjects:"المشاريع", navSponsors:"الرعاة", navTrans:"الشفافية", navZakat:"الزكاة", navDonate:"تبرع →", hero1:"نربط القارات،", hero2:"نبني الأمل", heroSub:"تبرعك يوصل الماء النظيف والتعليم والرعاية الصحية عبر أفريقيا.", heroBtn:"تبرع الآن", give:"امنح الأمل", live:"مباشر", live21:"مباشر 21", donateNow:"تبرع الآن", global:"الوجود العالمي", globalSub:"من إسطنبول وباكو إلى 22 دولة", globalMap:"تركيا • أذربيجان • أمريكا", globalClick:"انقر للاستكشاف →", lives:"حياة", projects:"مشروع", countries:"دولة", story:"قصتنا", since:"منذ 2021", storyDesc:"تأسست 2021، ولدت من فكرة الرحمة التركية والأذربيجانية.", storyBtn:"اقرأ قصتنا →", impactT:"تأثير 2024", water:"ماء نظيف", waterSub:"78k • 156 بئر", edu:"تعليم", eduSub:"3k • 12 مدرسة", health:"صحة", healthSub:"15k • 4 عيادة", viewProjects:"عرض كل المشاريع →", urgent:"نداءات عاجلة", viewAll:"عرض الكل 45 →", ramadan:"طرود غذاء رمضان", orphan:"كفالة يتيم", well:"بئر عميق", how:"كيف يصبح تبرعك أملاً • تتبع 100٪", s1t:"أنت تتبرع", s1d:"آمن", s2t:"ننفذ 72 ساعة", s2d:"يبدأ خلال 72 ساعة", s3t:"تحصل على إثبات", s3d:"فيديو", s4t:"تقرير الأثر", s4d:"تقرير مدقق", proof:"بث الإثبات المباشر", proof1:"افتتاح البئر #157", proof2:"120 طرد غذائي", proof3:"34 طفل", sponsorT:"مستويات الرعاية المؤسسية", bronze:"برونزي", bronzeD:"بئر واحد", silver:"فضي", silverD:"3 آبار", gold:"ذهبي", goldD:"مدرسة كاملة", platinum:"بلاتيني", platinumD:"مجمع قروي", viewTier:"عرض المستوى →", donorWall:"جدار المتبرعين", donorLive:"مباشر", zakatT:"حاسبة الزكاة", zakatSub:"أدخل إجمالي الثروة", zakatWealth:"الثروة", zakatDue:"الزكاة المستحقة", zakatBtn:"تبرع بالزكاة →", calcPlaceholder:"2500", videoT:"كل تبرع له فيديو إثبات", videoSub:"لقطات طائرة بدون طيار", trustT:"موثوق وآمن", finalT1:"سمّ بئراً اليوم", finalT2:"باسم عائلتك", finalSub:"اسم عائلتك على لوحة بئر في أوغندا", finalBtn:"تبرع ببئر – $2,500 →", whatsapp:"واتساب", footerLinks:"روابط", footerGive:"العطاء", footerStory:"قصتنا", footerWhere:"أين نعمل", footerZakat:"حاسبة الزكاة", footerDonate:"تبرع الآن", trLabel:"تركيا", azLabel:"أذربيجان", },
  fr: { navHome:"Accueil", navAbout:"À Propos", navWhere:"Où Nous Travaillons", navImpact:"Impact", navProjects:"Projets", navSponsors:"Sponsors", navTrans:"Transparence", navZakat:"Zakat", navDonate:"Faire un Don →", hero1:"Relier les Continents,", hero2:"Construire l'Espoir", heroSub:"Votre don apporte eau potable, éducation et santé en Afrique. 100% transparent.", heroBtn:"Faire un Don → $50 = 1 Mois d'Eau", give:"Donnez de l'Espoir", live:"EN DIRECT", live21:"EN DIRECT 21", donateNow:"Faire un Don", global:"Présence Mondiale", globalSub:"Istanbul & Bakou vers 22 nations", globalMap:"Turquie • Azerbaïdjan • USA • UK • Ouganda • Somalie • Niger", globalClick:"Cliquez pour explorer →", lives:"Vies", projects:"Projets", countries:"Pays", story:"Notre Histoire", since:"DEPUIS 2021", storyDesc:"Fondée 2021, née de l'idée: la compassion turque et azerbaïdjanaise peut changer l'Afrique.", storyBtn:"Lire Notre Histoire →", impactT:"Impact 2024", water:"Eau Potable", waterSub:"78k • 156 puits", edu:"Éducation", eduSub:"3k • 12 écoles", health:"Santé", healthSub:"15k • 4 cliniques", viewProjects:"Voir Tous les Projets →", urgent:"Appels Urgents", viewAll:"Voir Tout 45 →", ramadan:"Colis Alimentaires Ramadan", orphan:"Parrainage Orphelin", well:"Puits Profond – 800 Personnes", how:"Comment Votre Don Devient Espoir • Suivi 100%", s1t:"Vous Donnez", s1d:"SSL 256-bit sécurisé", s2t:"Nous Déployons 72H", s2d:"Démarre en 72h", s3t:"Vous Recevez Preuve", s3d:"Drone, interviews, GPS", s4t:"Rapport d'Impact", s4d:"Rapport audité", proof:"Flux de Preuves en Direct", proof1:"Puits #157 ouvert – 840 personnes", proof2:"120 colis livrés", proof3:"34 enfants traités", sponsorT:"Niveaux de Parrainage Entreprise", bronze:"Bronze • $1k-$5k", bronzeD:"1 puits ou 30 kits", silver:"Argent • $5k-$15k", silverD:"3 puits ou 1 classe", gold:"Or • $15k-$50k", goldD:"École complète", platinum:"Platine • $50k+", platinumD:"Complexe village", viewTier:"Voir Niveau →", donorWall:"Mur des Donateurs", donorLive:"LIVE", zakatT:"Calculateur Zakat • 2.5%", zakatSub:"Entrez richesse totale", zakatWealth:"Richesse", zakatDue:"Zakat Dû", zakatBtn:"Donner Zakat →", calcPlaceholder:"2500", videoT:"Chaque Don a une Preuve Vidéo", videoSub:"Drone, interviews", trustT:"Fiable & Sécurisé • 89% Terrain", finalT1:"Nommez un Puits Aujourd'hui", finalT2:"Après Votre Famille", finalSub:"Nom de famille sur plaque puits en Ouganda • Vidéo + GPS + Certificat en 7 jours", finalBtn:"Faire Don Puits – $2,500 →", whatsapp:"WhatsApp", footerLinks:"Liens", footerGive:"Donner", footerStory:"Notre Histoire", footerWhere:"Où Nous Travaillons", footerZakat:"Calculateur Zakat", footerDonate:"Faire un Don", trLabel:"Turquie", azLabel:"Azerbaïdjan", }
}
const Ctx = createContext<any>(null)
export function LanguageProvider({children}:{children:React.ReactNode}){
  const [lang,setLang]=useState("tr")
  useEffect(()=>{ const s=localStorage.getItem("vakif_lang"); if(s) setLang(s) },[])
  const change=(l:string)=>{ setLang(l); localStorage.setItem("vakif_lang",l); document.documentElement.lang=l; window.dispatchEvent(new Event("langChange")) }
  useEffect(()=>{ const h=()=>{ const s=localStorage.getItem("vakif_lang"); if(s) setLang(s)}; window.addEventListener("storage",h); window.addEventListener("langChange",h); return()=>{window.removeEventListener("storage",h); window.removeEventListener("langChange",h)}},[])
  const t=dict[lang]||dict.en
  return <Ctx.Provider value={{lang,t,change,dict}}>{children}</Ctx.Provider>
}
export const useLanguage=()=>useContext(Ctx)
